;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Copyright © 2026 Cristian Cezar Moisés <ethicalhacker@riseup.net>

(define-module (securityops packages torando-gui)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix build-system copy)
  #:use-module (gnu packages python)
  #:use-module (gnu packages tor)
  #:use-module (gnu packages linux)
  #:use-module ((guix licenses) #:prefix license:))

;;; torando-gui — loopback web GUI + root daemon that routes ONE local user's
;;; egress through Tor (transparent proxy + killswitch), automating the upstream
;;; torando iptables rules plus torrc/resolv.conf management.  Pure-Python
;;; (stdlib only), so it is built FROM SOURCE with copy-build-system — no
;;; compile, no patchelf.  Source is the vendored 1.4.1 release snapshot
;;; (vendored to keep the channel self-contained / buildable offline).  The two FHS shims call a
;;; bare `python3' and assume /usr/lib; the wrap-shims phase rewrites them to the
;;; store python3 and prepends the store bins of the tools the root daemon execs
;;; (iptables, chattr via e2fsprogs, tor), and points the systemd unit at the
;;; store binary — so the Guix package is self-contained (matches packaging/guix.scm
;;; in the upstream repo).  The user-facing `torando-gui' opens a native GTK4 +
;;; WebKitGTK window if that stack is on the user's profile, else falls back to
;;; the browser; the daemon itself needs neither, so they are NOT package inputs
;;; (add `gtk webkitgtk python-pygobject' to your profile for the native window).
(define-public torando-gui
  (package
    (name "torando-gui")
    (version "1.4.1")
    (source (local-file "sources/torando-gui-1.4.1-src.tar.gz"))
    (build-system copy-build-system)
    (inputs (list python tor iptables e2fsprogs))
    (arguments
     (list
      #:install-plan
      #~'(("backend/torando_gui" "lib/torando-gui/torando_gui")
          ("packaging/bin/torando-gui"  "bin/torando-gui")
          ("packaging/bin/torando-guid" "bin/torando-guid")
          ("packaging/systemd/torando-gui.service"
           "lib/systemd/system/torando-gui.service")
          ("packaging/polkit/co.securityops.torando-gui.policy"
           "share/polkit-1/actions/co.securityops.torando-gui.policy")
          ("packaging/polkit/49-torando-gui.rules"
           "share/polkit-1/rules.d/49-torando-gui.rules")
          ("packaging/desktop/torando-gui.desktop"
           "share/applications/torando-gui.desktop")
          ("README.md"       "share/doc/torando-gui/README.md")
          ("THREAT_MODEL.md" "share/doc/torando-gui/THREAT_MODEL.md")
          ("LICENSE"         "share/doc/torando-gui/LICENSE"))
      #:phases
      #~(modify-phases %standard-phases
          ;; No ELF payload (pure Python + /bin/sh shims).
          (delete 'strip)
          (delete 'validate-runpath)
          (add-after 'install 'wrap-shims
            (lambda* (#:key inputs outputs #:allow-other-keys)
              (let* ((out    (assoc-ref outputs "out"))
                     (lib    (string-append out "/lib/torando-gui"))
                     (python (string-append (assoc-ref inputs "python") "/bin/python3"))
                     (path   (string-join
                              (list (string-append (assoc-ref inputs "python") "/bin")
                                    (string-append (assoc-ref inputs "iptables") "/sbin")
                                    (string-append (assoc-ref inputs "iptables") "/bin")
                                    (string-append (assoc-ref inputs "e2fsprogs") "/sbin")
                                    (string-append (assoc-ref inputs "e2fsprogs") "/bin")
                                    (string-append (assoc-ref inputs "tor") "/bin"))
                              ":")))
                (define (write-shim name module)
                  (let ((p (string-append out "/bin/" name)))
                    (call-with-output-file p
                      (lambda (port)
                        (format port "#!/bin/sh
# Generated by the securityops channel: self-contained launcher.
export PYTHONPATH=\"~a${PYTHONPATH:+:$PYTHONPATH}\"
export PATH=\"~a${PATH:+:$PATH}\"
exec ~a -m ~a \"$@\"\n"
                                lib path python module)))
                    (chmod p #o755)))
                (write-shim "torando-gui"  "torando_gui.launcher")
                (write-shim "torando-guid" "torando_gui")
                (substitute* (string-append out "/lib/systemd/system/torando-gui.service")
                  (("/usr/bin/torando-guid")
                   (string-append out "/bin/torando-guid")))))))))
    (synopsis "Route a user's egress through Tor (transparent proxy + killswitch)")
    (description
     "Loopback web GUI that forces one local user's traffic through Tor's
TransPort and DNSPort and drops everything else from that user (a fail-closed
killswitch).  It automates the upstream torando iptables rules together with
torrc and resolv.conf management, adds an ip6tables IPv6 killswitch so v6 cannot
leak around Tor, and reports live bootstrap, DNS-leak and exit status.  Built
from source (pure Python); the shims and systemd unit are rewired to the store,
so the package is self-contained.  This is the Linux build of a project that
also targets macOS, the BSDs and Windows.")
    (home-page "https://codeberg.org/berkeley/torando-gui")
    (license license:agpl3)))
